key: 0d0YZ3246gRxJgGxyn3MEm7DL6iDt+M70ltvkRUh6vk4U9yA3z+NgOPsZcw8+Lg4KqJxWX1nlY5A4w6Et5BEmqFVGIqu3bF6uiLztJV8s3MCeQJJd6zp9OZRdLeRk4vhbqWYJzDPIzGe/6O7PmVF9gyzShd2F2ofqmz2k3aOGBX7O8+sQe/uBg8BcjSUPaG7UzPru855wr73WjRLNS2HoSCvvSjqQs/4XCg3ugcnSU3pUI/qb17YRhMjgbLkqIGlWDiib7Jta5NMCzGLHiqRM1qYli7Ho+D8qt5HiX0Ke0coy9J9QIc/wDQ+LKms3XiNe0qL7fZhJv6tvbFOB5FHNo92HzyqdqyOxX8+ZBJ9+j3xTTtp9m8LZ0ZuBp4SFHSSqdvIMa7E8Y6gm9aZXLUop3OE1fEdoRh4QHKeCT7lOFfTjK2qEkipZD4Ibbpz6/3So2gMsFwiroO1azFt5qFjlm/34oASClDJgjs4Voe2aAR591HHrm4u3J50bYgQNYqYDqyCu8Bzy3a4HC0xhCuzyjfyCYtwPASwbWORPQlozQ/tAtixwF7GdbCb/pLLpxDkNWdDz+VKXmCrJXGdy8l7eFny09bOrgb2NWQNqU6CGbyqnDuqWqyMOvYjA3PmTSsriD5cKt+w/5Q0W25mcyABAnmKDcnFYXqkrECEJlruwJfbCXGPJ2f7GTAn+1E9yAOkNhWLXuAU7yTVIVgHVoCmLBZslXbJEsLbQV7/xisG5/6zGogisGTE1vEeEFJ5j0uvdO7rpEiiYnyvNKMz4yKVzaAIrpFt2UaQNkEHDnfDjMZLMBlaZvPbmpj9njWhM0jLNXzuk5MD0e94HjxNzWM29B6FbnfvKfQUtALXOw23lgDR9EeFyVep8GSwKGs5G0LpYBdCKVTW0OYGweypeR+vcrUHrrTtZlculouu+PV1cbeejs0ErM2peUsx/t0ZuUnYwavYkrdWRCX9HbY6mnuQ8Q==
metrics:
  plugins:
    - name: jvmjolokia
      interval: 300
      enabled: true
      config:
        ip: 127.0.0.1
        password: admin
        protocol: http
        username: admin
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 30
