key: F+jesLKuyw9C8n+6bmHKRkYUtP6+5L5VlGcVVmic4sU5uy1leT5IMF/Qvk9CCI///H7jchKEKJp1kOePkG7Fue818xvG/YZ0hvnU3hDBVFU0JNbvd9UkBWk+ERIjpFbUFc/sjFc86wCOqRFovMy66hbPkS863VXuz78plV8dXwPIG8fmrPc77RdzFCXyn4L0ZSQWM4ZOMTYJLFRd++F0jIAdKjeRjpQHosBLYo1vaQmJu7sNf4yr57xxUiKnhRyJLiqUfuDI2X0OzeXylzi2Z8n0vBrpnDF2DcYNsamzKQATX8sWZrEAR+dwfA9nlfHx6tPyULTY4KHk7ULZgOi7yCYjOqYcogjeKLsRU35nf6IEIsEzgc+fEt5H1BuO1KC5UvLT5hKITi1wu3DzAwFGVlho/yDaylHhBgTpHvI4RLjGMiWOORsulvETCePmHTO7
metrics:
  plugins:
    - name: jvmjolokia
      interval: 300
      enabled: true
      config:
        ip: 127.0.0.1
        password: admin
        protocol: http
        username: admin
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
